/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.LoginController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            loginView: 'loginview'
        },

        control: {
            "loginview": {
                signInCommand: 'OnSignInCommand'
            }
        }
    },

    OnSignInCommand: function(view, username, password) {
        debugger;
        console.log('Username: ' + username + '\n' + 'Password: ' + password);
        var me = this,
            loginView = me.getLoginView();
        if (username.length === 0 || password.length === 0) {
            loginView.showSignInFailedMessage('Please enter your username and password.');
            return;
        }


        loginView.setMasked({
            xtype: 'loadmask',
            message: 'Signing In...'
        });



        Ext.Ajax.request({
            url :defLoginUrl,
            method: 'post',
            params: {
                j_username: username,
                j_password: password
            },
            success: function (response) {
            	
                var loginResponse = Ext.JSON.decode(response.responseText);
                console.log("ResponseText:\n" + response.responseText);
                if (loginResponse.success == true) {
console.log("Login Successful")
                    // The server will send a token that can be used throughout the app to confirm that the user is authenticated.
                    me.sessionToken = loginResponse.sessionToken;
                    me.signInSuccess();     //Just simulating success.
                } else {
console.log("Login Failed:" + loginResponse.message);
                    me.signInFailure(loginResponse.message);
                }
            },

            failure: function (response) {
                me.sessionToken = null;
                me.signInFailure('Login failed. Please try again later.');
     
            }

        });

    },

    signInSuccess: function() {

        console.log('Signed in.');
     /*   var loginView = this.getLoginView();
        mainMenuView = this.getMainMenuView();
        loginView.setMasked(false);

        Ext.Viewport.animateActiveItem(mainMenuView, this.getSlideLeftTransition());*/
        window.location = homeUrl + "/resources/app/";

    },

    getSlideLeftTransition: function() {
        return { type: 'slide', direction: 'left' };
    },

    signInFailure: function(message) {
        var loginView = this.getLoginView();
        loginView.showSignInFailedMessage(message);
        loginView.setMasked(false);
    }

});