/*
 * File: app/view/LoginView.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LoginView', {
    extend: 'Ext.Container',
    alias: 'widget.loginview',

    config: {
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'container',
                centered: true,
                height: '480px',
                width: '100%',
                items: [
                    {
                        xtype: 'formpanel',
                        centered: true,
                        height: '100%',
                        maxWidth: '320px',
                        padding: 10,
                        width: '320px',
                        items: [
                            {
                                xtype: 'image',
                                height: 201,
                                src: './images/loginpic.png'
                            },
                            {
                                xtype: 'spacer',
                                height: '10px'
                            },
                            {
                                xtype: 'label',
                                cls: 'loginHeading',
                                html: 'Thank you for logging in'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});