/*
 * File: app/view/ProfileView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.ProfileView', {
    extend: 'Ext.Panel',
    alias: 'widget.profileview',

    config: {
        items: [
            {
                xtype: 'navigationview',
                navigationBar: {
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            ui: 'confirm',
                            text: 'Save'
                        },
                        {
                            xtype: 'segmentedbutton',
                            align: 'right'
                        },
                        {
                            xtype: 'button',
                            ui: 'decline',
                            text: 'Cancel'
                        }
                    ]
                }
            },
            {
                xtype: 'formpanel',
                bottom: 0,
                id: 'profileform',
                itemId: 'profileform',
                left: 0,
                right: 0,
                top: 47,
                autoDestroy: false,
                items: [
                    {
                        xtype: 'tabpanel',
                        items: [
                            {
                                xtype: 'container',
                                bottom: 0,
                                id: 'profileformcontainer',
                                itemId: 'profileformcontainer',
                                top: 0,
                                layout: {
                                    align: 'center',
                                    pack: 'center',
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'titlebar',
                                        docked: 'top',
                                        id: 'profiletitlebar',
                                        itemId: 'profiletitlebar',
                                        title: 'Profile'
                                    },
                                    {
                                        xtype: 'fieldset',
                                        centered: true,
                                        id: 'credentialsfieldset',
                                        itemId: 'credentialsfieldset',
                                        maxWidth: 500,
                                        title: 'Credentials',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'usernamefield',
                                                itemId: 'usernamefield',
                                                label: 'Username',
                                                labelWidth: 150
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'passwordfield',
                                                itemId: 'passwordfield',
                                                label: 'Password',
                                                labelWidth: 150
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        centered: true,
                                        id: 'identityfieldset',
                                        itemId: 'identityfieldset',
                                        maxWidth: 500,
                                        title: 'Identity',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'firstnamefield',
                                                itemId: 'firstnamefield',
                                                label: 'Firstname',
                                                labelWidth: 150
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'lastnamefield',
                                                itemId: 'lastnamefield',
                                                label: 'Lastname',
                                                labelWidth: 150
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                bottom: 0,
                                id: 'billingformcontainer',
                                itemId: 'billingformcontainer',
                                left: 0,
                                right: 0,
                                top: 0,
                                layout: {
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'titlebar',
                                        docked: 'top',
                                        id: 'billingtitlebar',
                                        itemId: 'billingtitlebar',
                                        title: 'Billing'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    },

    setUsername: function(username) {
        debugger;
        var usernameField=  Ext.getCmp("usernamefield");
        usernameField.value = username;
    }

});