/*
 * File: app/view/ProfileView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ProfileView', {
    extend: 'Ext.Panel',
    alias: 'widget.profileview',

    config: {
        items: [
            {
                xtype: 'navigationview',
                navigationBar: {
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            ui: 'confirm',
                            text: 'Save'
                        },
                        {
                            xtype: 'segmentedbutton',
                            align: 'right',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Profile'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Billing'
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            ui: 'decline',
                            text: 'Cancel'
                        }
                    ]
                }
            },
            {
                xtype: 'profileform',
                bottom: 0,
                id: 'profileform',
                itemId: 'profileform',
                left: 0,
                right: 0,
                top: 47,
                items: [
                    {
                        xtype: 'carousel',
                        bottom: 0,
                        left: 0,
                        right: 0,
                        top: 0,
                        items: [
                            {
                                xtype: 'container',
                                bottom: 0,
                                left: 0,
                                right: 0,
                                top: 0,
                                layout: {
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'titlebar',
                                        docked: 'top',
                                        title: 'Profile'
                                    },
                                    {
                                        xtype: 'fieldset',
                                        bottom: 10,
                                        title: 'Credentials',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'usernamefield',
                                                itemId: 'usernamefield',
                                                label: 'Username',
                                                labelWidth: '35%'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'passwordfield',
                                                itemId: 'passwordfield',
                                                label: 'Password',
                                                labelWidth: '35%'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: 'Identity',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: 'Firstname',
                                                labelWidth: '35%'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: 'Lastname',
                                                labelWidth: '35%'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: 'Lastname',
                                                labelWidth: '35%'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                bottom: 0,
                                itemId: 'mycontainer6',
                                left: 0,
                                right: 0,
                                top: 0,
                                layout: {
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'titlebar',
                                        docked: 'top',
                                        title: 'Billing'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    },

    setUsername: function(username) {
        debugger;
        var usernameField=  Ext.getCmp("usernamefield");
        usernameField.value = username;
    }

});